export const REGISTER_FACEBOOK_USER_SUCCESS = 'REGISTER_FACEBOOK_USER_SUCCESS';
export const REGISTER_FACEBOOK_USER_REQUEST = 'REGISTER_FACEBOOK_USER_REQUEST';
export const REGISTER_FACEBOOK_USER_ERROR = 'REGISTER_FACEBOOK_USER_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const ADD_NEW_COCKTAIL_SUCCESS = 'ADD_NEW_COCKTAIL_SUCCESS';
export const ADD_NEW_COCKTAIL_REQUEST = 'ADD_NEW_COCKTAIL_REQUEST';
export const ADD_NEW_COCKTAIL_ERROR = 'ADD_NEW_COCKTAIL_ERROR';

export const GET_COCKTAILS_USER_SUCCESS = 'GET_COCKTAILS_USER_SUCCESS';
export const GET_COCKTAILS_USER_REQUEST = 'GET_COCKTAILS_USER_REQUEST';
export const GET_COCKTAILS_USER_ERROR = 'GET_COCKTAILS_USER_ERROR';

export const GET_ALL_COCKTAILS_SUCCESS = 'GET_ALL_COCKTAILS_SUCCESS';
export const GET_ALL_COCKTAILS_REQUEST = 'GET_ALL_COCKTAILS_REQUEST';
export const GET_ALL_COCKTAILS_ERROR = 'GET_ALL_COCKTAILS_ERROR';

export const CONTROL_PUBLISH_ERROR = 'CONTROL_PUBLISH_ERROR';
export const CONTROL_PUBLISH_SUCCESS = 'CONTROL_PUBLISH_SUCCESS';

export const DELETE_COCKTAIL_SUCCESS = 'DELETE_COCKTAIL_SUCCESS';
export const DELETE_COCKTAIL_ERROR = 'DELETE_COCKTAIL_ERROR';